version: "3.8"

services:
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
